"""empty message

Revision ID: bd291b631b47
Revises:
Create Date: 2023-06-01 15:23:31.326835

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "bd291b631b47"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samples",
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp on update current_timestamp"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samples_id"), "samples", ["id"], unique=False)
    op.create_index(op.f("ix_samples_name"), "samples", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samples_name"), table_name="samples")
    op.drop_index(op.f("ix_samples_id"), table_name="samples")
    op.drop_table("samples")
    # ### end Alembic commands ###
